# Hello Openshift Ingress Canary service
# Specific values are applied at runtime
kind: Service
apiVersion: v1
metadata:
  # name and namespace are set at runtime.
  annotations:
      service.beta.openshift.io/serving-cert-secret-name: canary-serving-cert
spec:
  type: ClusterIP
  ports:
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
